services:
  ssh:
    build:
      context: .
      args:
        VERSION: v0.1.7
    ports:
      - "22:2222"
    volumes:
      - ssh-host-key:/data
    environment:
      - RUST_LOG=info
      - SSH_HOST_KEY=/data/host_key
    restart: unless-stopped

volumes:
  ssh-host-key:
