app = 'ssh-seanyang-me'
primary_region = 'ord'

[build]

[env]
  SSH_ADDR = '0.0.0.0:2222'
  SSH_HOST_KEY = '/data/host_key'
  RUST_LOG = 'info'

[mounts]
  source = 'ssh_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 2222

  [[services.ports]]
    port = 22
